In [3]:
import numpy as np
import matplotlib.pyplot as plt
my_img = plt.imread('Train/1.jpg')
ImagesArray=np.ones([2400, 784])

#np.set_printoptions(threshold=sys.maxsize)


print("Assigning Targets")



Array0=np.ones([240, 784])
Array1=np.ones([240, 784])
Array2=np.ones([240, 784])
Array3=np.ones([240, 784])
Array4=np.ones([240, 784])
Array5=np.ones([240, 784])
Array6=np.ones([240, 784])
Array7=np.ones([240, 784])
Array8=np.ones([240, 784])
Array9=np.ones([240, 784])





#print(weightVectorTranspose)

print("Importing Images")

print("Testing Images")
testArray=np.ones([200, 784])

#print(testArray)
for i in range (0,200):
    Image=plt.imread('test/'+str(i+1)+'.jpg')
    Image= np.asmatrix(Image)
    Image =Image.flatten()
    Image=Image/255
    testArray[i]=Image
def InitializeArray(beginning,array):
    for i in range (0,240):
        Image=plt.imread('Train/'+str(i+1+240*beginning)+'.jpg')
        #print('Train/'+str(i+1+240*beginning)+'.jpg')
        Image =Image.flatten()
        Image=Image/255
        array[i]=Image
    
    
def InitializeAll():
    InitializeArray(0,Array0);
    InitializeArray(1,Array1);
    InitializeArray(2,Array2);
    InitializeArray(3,Array3);
    InitializeArray(4,Array4);
    InitializeArray(5,Array5);
    InitializeArray(6,Array6);
    InitializeArray(7,Array7);
    InitializeArray(8,Array8);
    InitializeArray(9,Array9);
    print(Array1.shape)
    
def MeanOfAll():
    InitializeAll()
    Mean0 =np.mean(Array0, axis=0).reshape((784, 1))
    Mean1 =np.mean(Array1, axis=0).reshape((784, 1))
    Mean2 =np.mean(Array2, axis=0).reshape((784, 1))
    Mean3 =np.mean(Array3, axis=0).reshape((784, 1))
    Mean4 =np.mean(Array4, axis=0).reshape((784, 1))
    Mean5 =np.mean(Array5, axis=0).reshape((784, 1))
    Mean6 =np.mean(Array6, axis=0).reshape((784, 1))
    Mean7 =np.mean(Array7, axis=0).reshape((784, 1))
    Mean8 =np.mean(Array8, axis=0).reshape((784, 1))
    Mean9 =np.mean(Array9, axis=0).reshape((784, 1))


    #print(Mean0.shape)
    return np.concatenate((Mean0,Mean1,Mean2,Mean3,Mean4,Mean5,Mean6,Mean7,Mean8,Mean9), axis=1).transpose()

    
    
def VarianceOfAll():
    InitializeAll()
    Standard0 =np.std(Array0, axis=0).reshape((784, 1))
    Standard1 =np.std(Array1, axis=0).reshape((784, 1))
    Standard2 =np.std(Array2, axis=0).reshape((784, 1))
    Standard3 =np.std(Array3, axis=0).reshape((784, 1))
    Standard4 =np.std(Array4, axis=0).reshape((784, 1))
    Standard5 =np.std(Array5, axis=0).reshape((784, 1))
    Standard6 =np.std(Array6, axis=0).reshape((784, 1))
    Standard7 =np.std(Array7, axis=0).reshape((784, 1))
    Standard8 =np.std(Array8, axis=0).reshape((784, 1))
    Standard9 =np.std(Array9, axis=0).reshape((784, 1))
    
 

    
    Standard0*=Standard0
    Standard1*=Standard1
    Standard2*=Standard2
    Standard3*=Standard3
    Standard4*=Standard4
    Standard5*=Standard5
    Standard6*=Standard6
    Standard7*=Standard7
    Standard8*=Standard8
    Standard9*=Standard9
    
    
    Standard0[Standard0 < .01]=0.01
    Standard1[Standard1 < .01]=0.01
    Standard2[Standard2 < .01]=0.01
    Standard3[Standard3 < .01]=0.01
    Standard4[Standard4 < .01]=0.01
    Standard5[Standard5 < .01]=0.01
    Standard6[Standard6 < .01]=0.01
    Standard7[Standard7 < .01]=0.01
    Standard8[Standard8 < .01]=0.01
    Standard9[Standard9 < .01]=0.01

    return np.concatenate((Standard0,Standard1,Standard2,Standard3,Standard4,Standard5,Standard6,Standard7,Standard8,Standard9), axis=1).transpose()

    
    
def Gaussian(mean,variance,x): 
    expontential=(x-mean)*(x-mean)
    expontential=expontential/(2*variance)
    expontential=expontential*-1
    expontential=np.exp(expontential)
    offset=np.sqrt(1/(2*np.pi*variance))
    
    return offset*expontential
    

def TestingPhase():
    image=testArray[50]
    
    MeanArray=MeanOfAll();
    VarianceArray=VarianceOfAll();
    #print(image.size)
    maxprop=0
    currentprop=1
    c=-1
    confusion_matrix=np.zeros((10, 10))
    for i in range(0,200):
        image=testArray[i]
        for j in range (0,10):
        #784 Features
            for k in range (0,MeanArray[j].size):
                currentprop*=Gaussian(MeanArray[j][k],VarianceArray[j][k],image[k])
            #print(currentprop)
            currentprop/=240
            if currentprop>maxprop:
                maxprop=currentprop
                c=j
            #Bug here
            currentprop=1
        maxprop=0
        if i in range(0, 20):
            #print(i)
                confusion_matrix[0][c]+=1
        if i in range(20, 40):
                confusion_matrix[1][c]+=1
        if i in range(40, 60):
                confusion_matrix[2][c]+=1
        if i in range(60, 80):
                confusion_matrix[3][c]+=1
        if i in range(80, 100):
                confusion_matrix[4][c]+=1
        if i in range(100, 120):
                confusion_matrix[5][c]+=1
        if i in range(120, 140):
                confusion_matrix[6][c]+=1
        if i in range(140, 160):
                confusion_matrix[7][c]+=1
        if i in range(160, 180):
                confusion_matrix[8][c]+=1
        if i in range(180, 200):
                confusion_matrix[9][c]+=1
    Accuracy=0;
    for i in range (0,10):
        Accuracy+=confusion_matrix[i][i]
    print("the Accuracy is "+str(Accuracy/200*100))
    print(confusion_matrix)
    matrix_image=np.zeros(np.array(confusion_matrix.shape) * 100)
    for j in range(confusion_matrix.shape[0]):
        for k in range(confusion_matrix.shape[1]):
            matrix_image[j * 100: (j+1) * 100, k * 100: (k+1) * 100] = confusion_matrix[j, k]
    plt.imsave( './Naive Bayes Confusion Matrix.jpg' , matrix_image)

            
                
                
            
if __name__ == "__main__":
    TestingPhase()
    

Assigning Targets
Importing Images
Testing Images
(240, 784)
(240, 784)


C:\Users\romyz\AppData\Local\Continuum\anaconda3\lib\site-packages\ipykernel_launcher.py:151: RuntimeWarning: overflow encountered in double_scalars


the Accuracy is 79.5
[[18.  0.  0.  0.  0.  0.  1.  0.  1.  0.]
 [ 0. 20.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0. 16.  0.  0.  1.  1.  0.  1.  1.]
 [ 0.  0.  0. 17.  0.  1.  0.  0.  2.  0.]
 [ 0.  0.  0.  0. 12.  0.  3.  0.  1.  4.]
 [ 0.  0.  0.  0.  2. 14.  0.  0.  3.  1.]
 [ 0.  0.  0.  0.  0.  0. 19.  0.  1.  0.]
 [ 0.  0.  0.  0.  3.  0.  0. 12.  0.  5.]
 [ 1.  0.  0.  0.  0.  0.  0.  0. 18.  1.]
 [ 1.  0.  0.  1.  3.  0.  0.  1.  1. 13.]]
