In [1]:
import numpy as np
import matplotlib.pyplot as plt
my_img = plt.imread('Train/1.jpg')
ImagesArray=np.ones([2400, 784])
onesArray=np.ones([2400, 1])

print("Assigning Targets")
c0=(np.ones((2400,1)))

c1=(np.ones((2400,1)))
c2=(np.ones((2400,1)))
c3=(np.ones((2400,1)))
c4=(np.ones((2400,1)))
c5=(np.ones((2400,1)))
c6=(np.ones((2400,1)))
c7=(np.ones((2400,1)))
c8=(np.ones((2400,1)))
c9=(np.ones((2400,1)))




for i in range(0,len(c0)):
    if not(i>=0 and i<=240):
        c0[i]=-1;
        
for i in range(0,len(c1)):
    if not(i>240 and i<=240*2):
        c1[i]=-1;
for i in range(0,len(c1)):
    if not(i>240*2 and i<=240*3):
        c2[i]=-1;
        
        
for i in range(0,len(c1)):
    if not(i>240*3 and i<=240*4):
        c3[i]=-1;
        
        
for i in range(0,len(c1)):
    if not(i>240*4 and i<=240*5):
        c4[i]=-1;
        
        
for i in range(0,len(c1)):
    if not(i>240*5 and i<=240*6):
        c5[i]=-1;
        
        
for i in range(0,len(c1)):
    if not(i>240*6 and i<=240*7):
        c6[i]=-1;
for i in range(0,len(c1)):
    if not(i>240*7 and i<=240*8):
        c7[i]=-1;
        
for i in range(0,len(c1)):
    if not(i>240*8 and i<=240*9):
        c8[i]=-1;
for i in range(0,len(c1)):
    if not(i>240*9 and i<=240*100):
        c9[i]=-1;


#print(weightVectorTranspose)

print("Importing Images")

for i in range (0,2400):
    Image=plt.imread('Train/'+str(i+1)+'.jpg')
    Image =Image.flatten()
    #print(Image)
    #print(len(Image))
    #print(ImagesArray.shape)
    ImagesArray[i]=Image
ImagesArray=np.append(ImagesArray, onesArray, axis=1)


print("Testing Images")
testArray=np.ones([200, 784])
onesArray=np.ones([200, 1])

#print(testArray)
for i in range (0,200):
    Image=plt.imread('test/'+str(i+1)+'.jpg')
    Image= np.asmatrix(Image)
    Image =Image.flatten()
    testArray[i]=Image

testArray=np.append(testArray, onesArray, axis=1)

#############Training phase###############
def OneClassOnerate(learningRate,numberClass):
    j=0
    i=-1
    weightVector=np.zeros((785))
    weightVector[0]=1
    #print(weightVector)
  
    for j in range(0,500):
        for i in range(0,2400):
        #print(i)
            #print(ImagesArray[i].shape)
            #print(weightVector.shape)

            #ImagesArray[i]=np.reshape(ImagesArray[i],(785,1))
            classification=(np.dot(weightVector,ImagesArray[i]))
            #print(classification)
            if(classification>=0):
                classification=1
            else:
                classification=-1
            if not (classification== numberClass[i]):
                #update Weight Vector
                #print(numberClass[i])
                AdditionOffset=np.multiply(ImagesArray[i],numberClass[i])
                AdditionOffset=np.multiply(AdditionOffset,learningRate)
                weightVector=np.add(weightVector,AdditionOffset)
    return weightVector
        
        
def AllClassesByRate(LearningRate=0.1):
    w0=OneClassOnerate(LearningRate,c0);
    w1=OneClassOnerate(LearningRate,c1);

    w2=OneClassOnerate(LearningRate,c2);
    w3=OneClassOnerate(LearningRate,c3);
    w4=OneClassOnerate(LearningRate,c4);
    w5=OneClassOnerate(LearningRate,c5);
    w6=OneClassOnerate(LearningRate,c6);
    w7=OneClassOnerate(LearningRate,c7);
    w8=OneClassOnerate(LearningRate,c8);
    w9=OneClassOnerate(LearningRate,c9);
    weights =[w0,w1,w2,w3,w4,w5,w6,w7,w8,w9]
    confusion_matrix=np.zeros((10, 10))
    for i in range(0,200):
        image0=testArray[i]
        output=np.dot(weights[0],image0)
        #print(output.shape)
        #print(w0.shape)
        #print(image0.shape)
        c=0;
        for j in range(0,len(weights)):
            output2=np.dot(weights[j],image0)
            if output2>output:
                output=output2;
                #print("Here")
                c=j
        #print(c)
        if i in range(0, 20):
            #print(i)
            confusion_matrix[0][c]+=1
        if i in range(20, 40):
            confusion_matrix[1][c]+=1
        if i in range(40, 60):
            confusion_matrix[2][c]+=1
        if i in range(60, 80):
            confusion_matrix[3][c]+=1
        if i in range(80, 100):
            confusion_matrix[4][c]+=1
        if i in range(100, 120):
            confusion_matrix[5][c]+=1
        if i in range(120, 140):
            confusion_matrix[6][c]+=1
        if i in range(140, 160):
            confusion_matrix[7][c]+=1
        if i in range(160, 180):
            confusion_matrix[8][c]+=1
        if i in range(180, 200):
            confusion_matrix[9][c]+=1
    #print(confusion_matrix)
    Accuracy=0.0;
    for i in range (0,10):
        Accuracy+=confusion_matrix[i][i]
    print("the Accuracy is "+str(Accuracy/200*100))
    print("the confusion matrix is ")
    print(confusion_matrix)
    matrix_image=np.zeros(np.array(confusion_matrix.shape) * 100)
    for j in range(confusion_matrix.shape[0]):
        for k in range(confusion_matrix.shape[1]):
            matrix_image[j * 100: (j+1) * 100, k * 100: (k+1) * 100] = confusion_matrix[j, k]
    plt.imsave( './Confusion-'+str(LearningRate)+'.jpg' , matrix_image)

    return weights
    
if __name__ == "__main__":
    print("Learning rate = 1 ")
    AllClassesByRate(1)
    print("Learning rate = 0.1 ")
    AllClassesByRate(0.1)
    print("Learning rate = 0.01 ")
    AllClassesByRate(0.01)
    print("Learning rate = 0.001 ")
    AllClassesByRate(0.001)
    print("Learning rate = 0.0001 ")
    AllClassesByRate(0.0001)
    print("Learning rate = 0.00001 ")
    AllClassesByRate(0.00001)
    print("Learning rate = 0.000001 ")
    AllClassesByRate(0.000001)
    print("Learning rate = 0.0000001 ")
    AllClassesByRate(0.0000001)
    print("Learning rate = 0.00000001 ")
    AllClassesByRate(0.00000001)
    print("Learning rate = 0.000000001 ")
    AllClassesByRate(0.000000001)







     

Assigning Targets
Importing Images
Testing Images
Learning rate = 1 
the Accuracy is 80.5
the confusion matrix is 
[[18.  0.  0.  0.  0.  0.  1.  1.  0.  0.]
 [ 0. 18.  1.  0.  0.  0.  0.  0.  1.  0.]
 [ 0.  1. 17.  0.  0.  1.  0.  0.  1.  0.]
 [ 0.  0.  1. 14.  0.  0.  0.  0.  3.  2.]
 [ 0.  0.  0.  0. 13.  3.  1.  0.  0.  3.]
 [ 0.  0.  1.  0.  1. 14.  0.  0.  4.  0.]
 [ 0.  0.  0.  0.  0.  1. 18.  0.  1.  0.]
 [ 0.  0.  0.  1.  0.  0.  0. 15.  0.  4.]
 [ 0.  0.  0.  0.  0.  0.  0.  0. 19.  1.]
 [ 1.  0.  0.  0.  0.  0.  0.  3.  1. 15.]]
Learning rate = 0.1 
the Accuracy is 81.5
the confusion matrix is 
[[18.  0.  0.  0.  0.  0.  1.  1.  0.  0.]
 [ 0. 18.  1.  0.  0.  0.  0.  0.  1.  0.]
 [ 0.  1. 17.  0.  0.  1.  0.  0.  1.  0.]
 [ 0.  0.  1. 15.  0.  0.  0.  0.  2.  2.]
 [ 0.  0.  0.  0. 13.  3.  1.  0.  0.  3.]
 [ 0.  0.  1.  0.  1. 15.  0.  0.  3.  0.]
 [ 0.  0.  0.  0.  0.  1. 18.  0.  1.  0.]
 [ 0.  0.  0.  0.  0.  0.  0. 15.  0.  5.]
 [ 0.  0.  0.  0.  0.  0.  0.  0. 19.  1.]
